FROM openjdk:17-alpine

WORKDIR /app

ARG JAR_FILE=target/spring-boot-docker-*.jar

COPY ${JAR_FILE} spring-boot-docker.jar

CMD [ "java", "-jar", "-Xmx1024M", "/app/spring-boot-docker.jar" ]

EXPOSE 9090