server:
  port: 8090

spring:
  config:
    activate:
      on-profile: staging
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    url:  ${SPRING_DATASOURCE_URL:jdbc:postgresql://stagingdb:5432/bookdb}
    hikari:
      poolName: Hikari
      auto-commit: false